module.exports = {
  VALID_SERIAL_NUMBER_TYPE: "valid",
  RECALLED_SERIAL_NUMBER_TYPE: "recalled",
  DECOMMISSIONED_SERIAL_NUMBER_TYPE: "decommissioned",
  PACKAGES_STORAGE_PATH: "/app/data/packages.json",
  DATA_STORAGE_PATH: "/app/data",
  PRODUCTS_TABLE: "products",
  LOGS_TABLE: "logs",
  SERIAL_NUMBERS_LOGS_TABLE: "serial_numbers_logs",
  PRODUCT_KEYSSI_STORAGE_TABLE: "productKeySSIs",
  BATCHES_STORAGE_TABLE: "batches",
  EPI_PROTOCOL_VERSION: "1.0",
  PRODUCT_DSU_MOUNT_POINT: "/product",
  BATCH_DSU_MOUNT_POINT: "/batch",
  BATCH_STORAGE_FILE: "/batch.json",
  PRODUCT_STORAGE_FILE: "/product.json",
  PRODUCT_IMAGE_FILE: "/image.png",
  LEAFLET_ATTACHMENT_FILE: "/leaflet.xml",
  SMPC_ATTACHMENT_FILE: "/smpc.xml",
  IMPORT_LOGS: "import-logs",
  SUCCESS_MAPPING_STATUS: "success",
  FAILED_MAPPING_STATUS: "failed",
  MISSING_PRODUCT_DSU: "Missing Product DSU",
  DSU_LOAD_FAIL: "Something went wrong. Could not load DSU",
  MISSING_BATCH_DSU: "Missing Batch DSU",
  MISSING_PRODUCT_VERSION: "Missing Product Version",
  LOG_TYPES: {
    PRODUCT: "PRODUCT_LOG",
    BATCH: "BATCH_LOG",
    PROD_PHOTO: "PRODUCT_PHOTO_LOG",
    LEAFLET_LOG: "LEAFLET_LOG"
  }
}
