module.exports = {
    TABLES: {
        AUDIT: 'audit',
        PRODUCTS: 'products',
        BATCHES: 'batches'
    },
    MESSAGE_TYPES: {
        LEAFLET: 'leaflet',
        SMPC: 'smpc',
        PRODUCT: 'product',
        BATCH: 'batch',
        PRODUCT_PHOTO: 'productPhoto'
    },
    OPERATIONS: {
        CREATE_PRODUCT: 'Created Product',
        CREATE_PRODUCT_IN_PROGRESS: 'Create Product In Progress',
        CREATE_PRODUCT_FAIL: 'Create Product Fail',
        UPDATE_PRODUCT: 'Updated Product',
        UPDATE_PRODUCT_IN_PROGRESS: 'Update Product In Progress',
        UPDATE_PRODUCT_FAIL: 'Updated Product Fail',
        CREATE_BATCH: 'Created Batch',
        CREATE_BATCH_IN_PROGRESS: 'Create Batch In Progress',
        CREATE_BATCH_FAIL: 'Create Batch Fail',
        UPDATE_BATCH: 'Updated Batch',
        UPDATE_BATCH_IN_PROGRESS: 'Update Batch In Progress',
        UPDATE_BATCH_FAIL: 'Update Batch Fail',
        ADD_LEAFLET: 'Added Leaflet',
        ADD_LEAFLET_IN_PROGRESS: 'Add Leaflet In Progress',
        ADD_LEAFLET_FAIL: 'Add Leaflet Fail',
        UPDATE_LEAFLET: 'Updated Leaflet',
        UPDATE_LEAFLET_IN_PROGRESS: 'Update Leaflet In Progress',
        UPDATE_LEAFLET_FAIL: 'Update Leaflet Fail',
        DELETE_LEAFLET: 'Deleted Leaflet',
        DELETE_LEAFLET_IN_PROGRESS: 'Delete Leaflet In Progress',
        DELETE_LEAFLET_FAIL: 'Delete Leaflet Fail',
        ADD_PRODUCT_PHOTO: 'Added ProductPhoto',
        ADD_PRODUCT_PHOTO_IN_PROGRESS: 'Add ProductPhoto In Progress',
        ADD_PRODUCT_PHOTO_FAIL: 'Add ProductPhoto Fail',
        UPDATE_PRODUCT_PHOTO: 'Updated ProductPhoto',
        UPDATE_PRODUCT_PHOTO_IN_PROGRESS: 'Update ProductPhoto In Progress',
        UPDATE_PRODUCT_PHOTO_FAIL: 'Update ProductPhoto Fail',
        DELETE_PRODUCT_PHOTO: 'Deleted ProductPhoto',
        DELETE_PRODUCT_PHOTO_IN_PROGRESS: 'Delete ProductPhoto In Progress',
        DELETE_PRODUCT_PHOTO_FAIL: 'Delete ProductPhoto Fail',
        ADD_SMPC: 'Created SMPC',
        UPDATE_SMPC: 'Updated SMPC',
        DELETE_SMPC: 'Deleted SMPC'
    },
    MODELS_CACHE_NAME: 'modelsCache'
}